[project]
name = "biofoundation"
version = "0.1.0"
description = "An ecosystem for users of biological foundation models"
requires-python = ">=3.9"
dependencies = [
    "datasets",
    "numpy",
    "pandas",
    "scikit-learn",
    "transformers[torch]",
]
